import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Provably Fair | Midnight Riches",
  description:
    "Learn how Midnight Riches uses cryptographic algorithms to ensure every spin is provably fair and independently verifiable.",
};

export default function ProvablyFairPage() {
  return (
    <div className="min-h-screen bg-[var(--bg-primary)] px-4 py-20">
      <div className="mx-auto max-w-4xl">
        <Link
          href="/"
          className="mb-10 inline-flex items-center gap-2 text-sm text-[var(--text-muted)] transition-colors hover:text-[var(--text-primary)]"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
          >
            <path d="M19 12H5" />
            <path d="m12 19-7-7 7-7" />
          </svg>
          Back to Home
        </Link>

        <header className="mb-12">
          <h1
            className="mb-4 text-4xl font-bold tracking-tight text-[var(--text-primary)]"
            style={{ fontFamily: "var(--font-garamond)" }}
          >
            Provably Fair
          </h1>
          <p className="text-sm text-[var(--text-muted)]">
            Last updated: March 18, 2026
          </p>
        </header>

        <div className="space-y-8">
          {/* Introduction */}
          <section className="rounded-xl border border-[var(--glass-border)] bg-[var(--bg-card)] p-6 md:p-8">
            <p className="leading-relaxed text-[var(--text-secondary)]">
              At Midnight Riches, we believe trust is earned through
              transparency. Our Provably Fair system uses cryptographic
              algorithms to ensure that every single game outcome is genuinely
              random, tamper-proof, and independently verifiable by you. Neither
              the house nor the player can manipulate the outcome after a bet is
              placed.
            </p>
          </section>

          {/* What is Provably Fair? */}
          <section className="rounded-xl border border-[var(--glass-border)] bg-[var(--bg-card)] p-6 md:p-8">
            <h2
              className="mb-4 text-2xl font-semibold text-[var(--text-primary)]"
              style={{ fontFamily: "var(--font-garamond)" }}
            >
              What Does &quot;Provably Fair&quot; Mean?
            </h2>
            <div className="space-y-4 leading-relaxed text-[var(--text-secondary)]">
              <p>
                Provably fair is a cryptographic framework that allows players to
                independently verify that game outcomes were determined fairly
                and were not manipulated by the operator. Unlike traditional
                casinos where you must trust the house, provably fair gaming
                provides mathematical proof that every result is legitimate.
              </p>
              <p>
                The system works by combining inputs from both the server and
                the player to generate game outcomes. Because the player
                contributes to the randomness, the server alone cannot
                predetermine results. And because the server&apos;s contribution
                is committed in advance (via a hash), it cannot be changed after
                your bet is placed.
              </p>
            </div>
          </section>

          {/* How It Works */}
          <section className="rounded-xl border border-[var(--glass-border)] bg-[var(--bg-card)] p-6 md:p-8">
            <h2
              className="mb-4 text-2xl font-semibold text-[var(--text-primary)]"
              style={{ fontFamily: "var(--font-garamond)" }}
            >
              How It Works
            </h2>
            <div className="space-y-6 leading-relaxed text-[var(--text-secondary)]">
              <p>
                Our system relies on three key components that work together to
                produce verifiable randomness:
              </p>

              <div className="rounded-lg border border-[var(--glass-border)] bg-[var(--bg-secondary)] p-5">
                <h3 className="mb-2 text-lg font-medium text-[var(--text-primary)]">
                  Server Seed
                </h3>
                <p>
                  A cryptographically random 256-bit value generated by our
                  server using a secure random number generator. Before any game
                  begins, we provide you with a SHA-256 hash of the server seed.
                  This hash acts as a commitment &mdash; it proves the server
                  seed was fixed before your bet, but does not reveal the seed
                  itself until after the game round concludes.
                </p>
              </div>

              <div className="rounded-lg border border-[var(--glass-border)] bg-[var(--bg-secondary)] p-5">
                <h3 className="mb-2 text-lg font-medium text-[var(--text-primary)]">
                  Client Seed
                </h3>
                <p>
                  A value provided by you, the player. We generate a default
                  client seed for convenience, but you may change it at any time
                  before placing a bet. This ensures the player has direct
                  influence over the randomness of the outcome. The server
                  cannot predict or control your client seed.
                </p>
              </div>

              <div className="rounded-lg border border-[var(--glass-border)] bg-[var(--bg-secondary)] p-5">
                <h3 className="mb-2 text-lg font-medium text-[var(--text-primary)]">
                  Nonce
                </h3>
                <p>
                  A sequential counter that starts at zero and increments by one
                  with each bet placed using the current server seed and client
                  seed pair. The nonce ensures that even with the same seeds,
                  every game round produces a unique outcome.
                </p>
              </div>
            </div>
          </section>

          {/* The Algorithm */}
          <section className="rounded-xl border border-[var(--glass-border)] bg-[var(--bg-card)] p-6 md:p-8">
            <h2
              className="mb-4 text-2xl font-semibold text-[var(--text-primary)]"
              style={{ fontFamily: "var(--font-garamond)" }}
            >
              The Algorithm: HMAC-SHA256
            </h2>
            <div className="space-y-4 leading-relaxed text-[var(--text-secondary)]">
              <p>
                The game outcome is derived using HMAC-SHA256, a
                cryptographically secure hash-based message authentication code.
                Here is how the computation works:
              </p>

              <div className="overflow-x-auto rounded-lg border border-[var(--glass-border)] bg-[var(--bg-secondary)] p-5">
                <code className="block whitespace-pre text-sm text-[var(--text-primary)]">
                  {`hash = HMAC-SHA256(serverSeed, clientSeed:nonce)

// Example:
serverSeed = "a3f1c9..."
clientSeed = "player_custom_seed"
nonce      = 42

hash = HMAC-SHA256("a3f1c9...", "player_custom_seed:42")
// Result: "e7b4a1d9c3f2..."  (64 hex characters)`}
                </code>
              </div>

              <p>
                The resulting 64-character hexadecimal hash is then converted
                into the game outcome:
              </p>

              <ol className="ml-6 list-decimal space-y-3">
                <li>
                  <strong>Hash generation:</strong> The HMAC-SHA256 function
                  takes the server seed as the key and the combination of client
                  seed and nonce as the message, producing a 256-bit hash.
                </li>
                <li>
                  <strong>Byte extraction:</strong> We take specific bytes from
                  the hash to generate random values for each reel position. For
                  our 3x3 slot grid, we extract 9 values (3 reels, 3 rows
                  each).
                </li>
                <li>
                  <strong>Symbol mapping:</strong> Each extracted value is mapped
                  to a symbol on the reel strip using a weighted distribution
                  table. This ensures the mathematical house edge remains
                  consistent and transparent.
                </li>
                <li>
                  <strong>Result determination:</strong> The mapped symbols form
                  the final grid, which is then evaluated against the payline
                  table to determine wins.
                </li>
              </ol>
            </div>
          </section>

          {/* Step-by-Step Verification */}
          <section className="rounded-xl border border-[var(--glass-border)] bg-[var(--bg-card)] p-6 md:p-8">
            <h2
              className="mb-4 text-2xl font-semibold text-[var(--text-primary)]"
              style={{ fontFamily: "var(--font-garamond)" }}
            >
              How to Verify a Spin
            </h2>
            <div className="space-y-4 leading-relaxed text-[var(--text-secondary)]">
              <p>
                After a game round, you can verify the fairness of the outcome
                by following these steps:
              </p>

              <ol className="ml-6 list-decimal space-y-4">
                <li>
                  <strong>Note the server seed hash:</strong> Before each game
                  session, you are shown the SHA-256 hash of the server seed.
                  Save this hash &mdash; it proves the seed was locked in before
                  play began.
                </li>
                <li>
                  <strong>Set your client seed (optional):</strong> You can
                  change your client seed at any time before spinning. Use any
                  random string you choose.
                </li>
                <li>
                  <strong>Play your round:</strong> Place your bet and spin.
                  The nonce increments automatically.
                </li>
                <li>
                  <strong>Reveal the server seed:</strong> After you rotate to
                  a new server seed (or end your session), the previous server
                  seed is revealed. You can find it in your game history.
                </li>
                <li>
                  <strong>Verify the hash:</strong> Compute SHA-256 of the
                  revealed server seed. It must match the hash you were shown
                  before the game. If it matches, the seed was not changed.
                </li>
                <li>
                  <strong>Recompute the outcome:</strong> Using the server
                  seed, your client seed, and the nonce, compute
                  HMAC-SHA256 and map the result to symbols. The result should
                  exactly match the outcome you received.
                </li>
              </ol>

              <div className="rounded-lg border border-[var(--glass-border)] bg-[var(--bg-secondary)] p-5">
                <p className="text-sm text-[var(--text-muted)]">
                  <strong>Tip:</strong> You can use any online HMAC-SHA256
                  calculator or write a simple script to verify outcomes. We
                  also provide a built-in verification tool in your game history
                  that automates this process.
                </p>
              </div>
            </div>
          </section>

          {/* RNG Technical Details */}
          <section className="rounded-xl border border-[var(--glass-border)] bg-[var(--bg-card)] p-6 md:p-8">
            <h2
              className="mb-4 text-2xl font-semibold text-[var(--text-primary)]"
              style={{ fontFamily: "var(--font-garamond)" }}
            >
              Random Number Generation
            </h2>
            <div className="space-y-4 leading-relaxed text-[var(--text-secondary)]">
              <p>
                Our random number generator is built on the Web Crypto API
                (<code className="rounded bg-[var(--bg-secondary)] px-1.5 py-0.5 text-sm">crypto.getRandomValues()</code>),
                which provides cryptographically secure pseudorandom numbers
                sourced from the operating system&apos;s entropy pool. Key
                properties include:
              </p>
              <ul className="ml-6 list-disc space-y-2">
                <li>
                  <strong>Entropy source:</strong> The OS kernel&apos;s CSPRNG,
                  seeded by hardware entropy (timing jitter, interrupt data,
                  hardware RNG where available).
                </li>
                <li>
                  <strong>Bit depth:</strong> 256-bit server seeds providing
                  2^256 possible values &mdash; a number larger than the
                  estimated atoms in the observable universe.
                </li>
                <li>
                  <strong>Unpredictability:</strong> Each output is
                  computationally indistinguishable from true randomness. No
                  party can predict the next value, even with knowledge of all
                  previous outputs.
                </li>
                <li>
                  <strong>No seed reuse:</strong> Server seeds are rotated
                  regularly and are never reused across sessions.
                </li>
              </ul>
            </div>
          </section>

          {/* Third-Party Auditing */}
          <section className="rounded-xl border border-[var(--glass-border)] bg-[var(--bg-card)] p-6 md:p-8">
            <h2
              className="mb-4 text-2xl font-semibold text-[var(--text-primary)]"
              style={{ fontFamily: "var(--font-garamond)" }}
            >
              Third-Party Auditing
            </h2>
            <div className="space-y-4 leading-relaxed text-[var(--text-secondary)]">
              <p>
                In addition to our provably fair system, which allows individual
                verification, we engage independent third-party auditors to
                conduct periodic reviews of our platform. These audits cover:
              </p>
              <ul className="ml-6 list-disc space-y-2">
                <li>
                  <strong>RNG integrity testing:</strong> Statistical analysis
                  of millions of game outcomes to ensure proper randomness
                  distribution (Diehard tests, NIST SP 800-22 test suite).
                </li>
                <li>
                  <strong>Payout verification:</strong> Confirmation that actual
                  return-to-player (RTP) rates align with the theoretical values
                  published for each game.
                </li>
                <li>
                  <strong>Code review:</strong> Security audit of the game
                  engine and provably fair implementation to ensure no
                  backdoors or manipulation vectors exist.
                </li>
                <li>
                  <strong>Compliance checks:</strong> Verification that our
                  platform meets applicable regulatory requirements.
                </li>
              </ul>
              <p>
                Audit reports are published periodically and available upon
                request by contacting our support team.
              </p>
            </div>
          </section>

          {/* Transparency Commitment */}
          <section className="rounded-xl border border-[var(--glass-border)] bg-[var(--bg-card)] p-6 md:p-8">
            <h2
              className="mb-4 text-2xl font-semibold text-[var(--text-primary)]"
              style={{ fontFamily: "var(--font-garamond)" }}
            >
              Our Transparency Commitment
            </h2>
            <div className="space-y-4 leading-relaxed text-[var(--text-secondary)]">
              <p>We are committed to full transparency in our operations:</p>
              <ul className="ml-6 list-disc space-y-2">
                <li>
                  <strong>Open payout tables:</strong> All symbol weights,
                  payline configurations, and payout multipliers are publicly
                  documented.
                </li>
                <li>
                  <strong>Published house edge:</strong> The theoretical RTP
                  for each game variant is clearly displayed before you play.
                </li>
                <li>
                  <strong>Complete game history:</strong> Every spin you make is
                  recorded with all inputs (server seed hash, client seed,
                  nonce) so you can verify any past result at any time.
                </li>
                <li>
                  <strong>Seed rotation transparency:</strong> You control when
                  to rotate seeds. The previous server seed is always revealed
                  upon rotation so you can run verification.
                </li>
              </ul>
            </div>
          </section>

          {/* Questions */}
          <section className="rounded-xl border border-[var(--glass-border)] bg-[var(--bg-card)] p-6 md:p-8">
            <h2
              className="mb-4 text-2xl font-semibold text-[var(--text-primary)]"
              style={{ fontFamily: "var(--font-garamond)" }}
            >
              Questions?
            </h2>
            <div className="space-y-4 leading-relaxed text-[var(--text-secondary)]">
              <p>
                If you have questions about our provably fair system or need
                assistance verifying a game outcome, our support team is here to
                help:
              </p>
              <ul className="ml-6 list-disc space-y-2">
                <li>
                  Email:{" "}
                  <a
                    href="mailto:fairness@midnightriches.com"
                    className="underline underline-offset-4 hover:text-[var(--text-primary)]"
                  >
                    fairness@midnightriches.com
                  </a>
                </li>
                <li>
                  Support:{" "}
                  <a
                    href="mailto:support@midnightriches.com"
                    className="underline underline-offset-4 hover:text-[var(--text-primary)]"
                  >
                    support@midnightriches.com
                  </a>
                </li>
              </ul>
            </div>
          </section>

          {/* Footer */}
          <footer className="pt-4 text-center text-sm text-[var(--text-muted)]">
            <p>
              &copy; {new Date().getFullYear()} Midnight Riches. All rights
              reserved.
            </p>
          </footer>
        </div>
      </div>
    </div>
  );
}
